<a href="https://colab.research.google.com/github/SarveshKadam167/MachineLearning/blob/main/Performance/Model_Evaluation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Model Evaluation

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [2]:
dataset = pd.read_csv('Data.csv')
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [3]:
print(X)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


In [4]:
print(y)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]


## Splitting the dataset into the Training set and Test set


In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

## Multiple Linear Regression

In [6]:
from sklearn.linear_model import LinearRegression
lin_reg_1 = LinearRegression()
lin_reg_1.fit(X_train, y_train)
y_pred_mlr = lin_reg_1.predict(X_test)

In [7]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred_mlr)

0.9325315554761303

## Polynomial Linear Regression

In [8]:
from sklearn.preprocessing import PolynomialFeatures
poly_reg = PolynomialFeatures(degree = 4)
X_poly = poly_reg.fit_transform(X_train)
lin_reg_2 = LinearRegression()
lin_reg_2.fit(X_poly,y_train)
y_pred_plr = lin_reg_2.predict(poly_reg.transform(X_test))

In [9]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred_plr)

0.9455261542316076

##Support Vector Regression

In [10]:
from sklearn.preprocessing import StandardScaler
scaler_X = StandardScaler()
X_train_scaled = scaler_X.fit_transform(X_train)
scaler_y = StandardScaler()
y_train_scaled = scaler_y.fit_transform(y_train.reshape(len(y_train),1))

In [11]:
print(X_train)

[[  11.22   43.13 1017.24   80.9 ]
 [  13.67   54.3  1015.92   75.42]
 [  32.84   77.95 1014.68   45.8 ]
 ...
 [  16.81   38.52 1018.26   75.21]
 [  12.8    41.16 1022.43   86.19]
 [  32.32   67.9  1006.08   37.93]]


In [12]:
print(y_train)

[473.93 467.87 431.97 ... 459.01 462.72 428.12]


In [13]:
print(X_train_scaled)

[[-1.13572795 -0.88685592  0.67357894  0.52070558]
 [-0.80630243 -0.00971567  0.45145467  0.14531044]
 [ 1.77128416  1.84743445  0.24279248 -1.88374143]
 ...
 [-0.38409993 -1.24886277  0.84522042  0.13092486]
 [-0.9232821  -1.04155299  1.54693117  0.8830852 ]
 [ 1.70136528  1.05824381 -1.20438076 -2.42285818]]


In [14]:
print(y_train_scaled)

[[ 1.15069786]
 [ 0.79540777]
 [-1.30936356]
 ...
 [ 0.27595724]
 [ 0.49346982]
 [-1.53508417]]


In [15]:
from sklearn.svm import SVR
svr_reg = SVR(kernel = 'rbf')
svr_reg.fit(X_train_scaled,y_train_scaled)
X_test_scaled = scaler_X.transform(X_test)
y_test_scaled = scaler_y.transform(y_test.reshape(len(y_test),1))
y_pred_svr = svr_reg.predict(X_test_scaled)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [16]:
from sklearn.metrics import r2_score
r2_score(y_test_scaled, y_pred_svr)

0.9480784049986258

## Decision Tree Regression

In [17]:
from sklearn.tree import DecisionTreeRegressor
dtr_reg = DecisionTreeRegressor(random_state=0)
dtr_reg.fit(X_train,y_train)
y_pred_dtr = dtr_reg.predict(X_test)

In [18]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred_dtr)

0.922905874177941

## Support Vector Regressor

In [19]:
from sklearn.ensemble import RandomForestRegressor
rfr_reg = RandomForestRegressor(n_estimators=10, random_state=0)
rfr_reg.fit(X_train,y_train)
y_pred_rfr = rfr_reg.predict(X_test)

In [20]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred_rfr)

0.9615908334363876